# Generated by Django 4.1.6 on 2023-02-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dcu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gwId', models.BigIntegerField(error_messages={'unique: gwId already present'}, unique=True)),
                ('timestamp', models.BigIntegerField()),
                ('debugServerTime', models.DateTimeField()),
                ('last_update_time', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'dcu_status',
            },
        ),
        migrations.CreateModel(
            name='DcuNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeId', models.IntegerField(error_messages={'unique: nodeId already present'}, unique=True)),
                ('gwId', models.BigIntegerField()),
                ('sinkId', models.CharField(max_length=10)),
                ('sinkNo', models.IntegerField()),
                ('timestamp', models.BigIntegerField()),
                ('debugServerTime', models.DateTimeField()),
                ('last_update_time', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'dcu_node_mapping',
            },
        ),
        migrations.CreateModel(
            name='DuplicateMeterNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeId', models.IntegerField()),
                ('meterNumber', models.CharField(max_length=20)),
                ('existingMeterNumber', models.CharField(max_length=20)),
                ('meterMaker', models.CharField(max_length=50)),
                ('rfMeterType', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.BigIntegerField()),
                ('debugServerTime', models.DateTimeField()),
                ('last_update_time', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'duplicate_meter_node_mapping',
            },
        ),
        migrations.CreateModel(
            name='MeterNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeId', models.IntegerField(unique=True)),
                ('meterNumber', models.CharField(max_length=20, unique=True)),
                ('meterMaker', models.CharField(max_length=50)),
                ('rfMeterType', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.BigIntegerField()),
                ('debugServerTime', models.DateTimeField()),
                ('last_update_time', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'meter_node_mapping',
            },
        ),
        migrations.AddConstraint(
            model_name='meternode',
            constraint=models.UniqueConstraint(fields=('nodeId', 'meterNumber'), name='Unique_nodeId_meterNumber'),
        ),
    ]
